# Generated by Django 6.1.2 on 2026-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_station_lat_lon_idx'), models.Index(fields=['state'], name='fuel_station_state_idx'), models.Index(fields=['retail_price'], name='fuel_station_price_idx')],
            },
        ),
    ]
